version: '2.1'

services:
#  redis:
#    container_name: redis
#    image: redis:alpine
#    healthcheck:
#        test: exit 0

  pcgr-webservice:
    container_name: pcgr-webservice
    build: .
    volumes:
      - '.:/usr/src/app'
      - './uploads:/usr/src/app/uploads'
      - './reports:/usr/src/app/reports'
      - '/mnt/pcgr:/usr/src/app/pcgr'
    ports:
      - 5000:5000
#    depends_on:
#      redis:
#        condition: service_healthy
    environment:
        - APP_SETTINGS=server.config.DevelopmentConfig
